enabled: false
hotspotapi:
  image:
    repository: waiter
    tag: 1.0
  resources:
    requests:
      memory: "30Mi"
      cpu: "10m"
    limits:
      memory: "128Mi"
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  config:
  secrets:
